/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_JAWTUtils */

#ifndef _Included_net_sf_jdshow_JAWTUtils
#define _Included_net_sf_jdshow_JAWTUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_JAWTUtils
 * Method:    getWindowHandle
 * Signature: (Ljava/awt/Canvas;)J
 */
JNIEXPORT jlong JNICALL Java_net_sf_jdshow_JAWTUtils_getWindowHandle
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
