/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_IMediaSeeking */

#ifndef _Included_net_sf_jdshow_IMediaSeeking
#define _Included_net_sf_jdshow_IMediaSeeking
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_NoPositioning
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_NoPositioning 0L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_AbsolutePositioning
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_AbsolutePositioning 1L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_RelativePositioning
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_RelativePositioning 2L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_IncrementalPositioning
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_IncrementalPositioning 3L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_PositioningBitsMask
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_PositioningBitsMask 3L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_SeekToKeyFrame
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_SeekToKeyFrame 4L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_ReturnTime
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_ReturnTime 8L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_Segment
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_Segment 16L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_NoFlush
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_NoFlush 32L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanSeekAbsolute
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanSeekAbsolute 1L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanSeekForwards
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanSeekForwards 2L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanSeekBackwards
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanSeekBackwards 4L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanGetCurrentPos
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanGetCurrentPos 8L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanGetStopPos
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanGetStopPos 16L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanGetDuration
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanGetDuration 32L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanPlayBackwards
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanPlayBackwards 64L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanDoSegments
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_CanDoSegments 128L
#undef net_sf_jdshow_IMediaSeeking_AM_SEEKING_Source
#define net_sf_jdshow_IMediaSeeking_AM_SEEKING_Source 256L
/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    GetPositions
 * Signature: ([J[J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaSeeking_GetPositions
  (JNIEnv *, jobject, jlongArray, jlongArray);

/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    SetPositions
 * Signature: ([JI[JI)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaSeeking_SetPositions
  (JNIEnv *, jobject, jlongArray, jint, jlongArray, jint);

/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    SetRate
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaSeeking_SetRate
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    GetRate
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaSeeking_GetRate
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    GetDuration
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaSeeking_GetDuration
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    GetCurrentPosition
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaSeeking_GetCurrentPosition
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     net_sf_jdshow_IMediaSeeking
 * Method:    Init_IID
 * Signature: (Lnet/sf/jdshow/GUID;)Lnet/sf/jdshow/GUID;
 */
JNIEXPORT jobject JNICALL Java_net_sf_jdshow_IMediaSeeking_Init_1IID
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
