/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_IMediaControl */

#ifndef _Included_net_sf_jdshow_IMediaControl
#define _Included_net_sf_jdshow_IMediaControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_IMediaControl
 * Method:    Run
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaControl_Run
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jdshow_IMediaControl
 * Method:    Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IMediaControl_Stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
