/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_WindowlessVMR */

#ifndef _Included_net_sf_jdshow_WindowlessVMR
#define _Included_net_sf_jdshow_WindowlessVMR
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_WindowlessVMR
 * Method:    InitWindowlessVMR
 * Signature: (JJ[J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_WindowlessVMR_InitWindowlessVMR
  (JNIEnv *, jclass, jlong, jlong, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
