/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_IVideoWindow */

#ifndef _Included_net_sf_jdshow_IVideoWindow
#define _Included_net_sf_jdshow_IVideoWindow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    put_Owner
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_put_1Owner
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    put_WindowStyle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_put_1WindowStyle
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    put_MessageDrain
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_put_1MessageDrain
  (JNIEnv *, jobject, jlong);

/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    put_Top
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_put_1Top
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    put_Left
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_put_1Left
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    get_Width
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_get_1Width
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     net_sf_jdshow_IVideoWindow
 * Method:    get_Height
 * Signature: ([J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IVideoWindow_get_1Height
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
