/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_IGraphBuilder */

#ifndef _Included_net_sf_jdshow_IGraphBuilder
#define _Included_net_sf_jdshow_IGraphBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_IGraphBuilder
 * Method:    RenderFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IGraphBuilder_RenderFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_sf_jdshow_IGraphBuilder
 * Method:    Init_IID
 * Signature: (Lnet/sf/jdshow/GUID;)Lnet/sf/jdshow/GUID;
 */
JNIEXPORT jobject JNICALL Java_net_sf_jdshow_IGraphBuilder_Init_1IID
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
