/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_WindowedRendering */

#ifndef _Included_net_sf_jdshow_WindowedRendering
#define _Included_net_sf_jdshow_WindowedRendering
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_WindowedRendering
 * Method:    InitWindowedRendering
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_WindowedRendering_InitWindowedRendering
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
