/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_IUnknown */

#ifndef _Included_net_sf_jdshow_IUnknown
#define _Included_net_sf_jdshow_IUnknown
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_jdshow_IUnknown
 * Method:    Release
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_sf_jdshow_IUnknown_Release
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jdshow_IUnknown
 * Method:    QueryInterface
 * Signature: (Lnet/sf/jdshow/GUID;[J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_IUnknown_QueryInterface
  (JNIEnv *, jobject, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
