/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jdshow_Com */

#ifndef _Included_net_sf_jdshow_Com
#define _Included_net_sf_jdshow_Com
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_jdshow_Com_S_OK
#define net_sf_jdshow_Com_S_OK 0L
#undef net_sf_jdshow_Com_WS_OVERLAPPED
#define net_sf_jdshow_Com_WS_OVERLAPPED 0L
#undef net_sf_jdshow_Com_WS_POPUP
#define net_sf_jdshow_Com_WS_POPUP -2147483648L
#undef net_sf_jdshow_Com_WS_CHILD
#define net_sf_jdshow_Com_WS_CHILD 1073741824L
#undef net_sf_jdshow_Com_WS_MINIMIZE
#define net_sf_jdshow_Com_WS_MINIMIZE 536870912L
#undef net_sf_jdshow_Com_WS_VISIBLE
#define net_sf_jdshow_Com_WS_VISIBLE 268435456L
#undef net_sf_jdshow_Com_WS_DISABLED
#define net_sf_jdshow_Com_WS_DISABLED 134217728L
#undef net_sf_jdshow_Com_WS_CLIPSIBLINGS
#define net_sf_jdshow_Com_WS_CLIPSIBLINGS 67108864L
#undef net_sf_jdshow_Com_WS_CLIPCHILDREN
#define net_sf_jdshow_Com_WS_CLIPCHILDREN 33554432L
#undef net_sf_jdshow_Com_WS_MAXIMIZE
#define net_sf_jdshow_Com_WS_MAXIMIZE 16777216L
#undef net_sf_jdshow_Com_WS_CAPTION
#define net_sf_jdshow_Com_WS_CAPTION 12582912L
#undef net_sf_jdshow_Com_WS_BORDER
#define net_sf_jdshow_Com_WS_BORDER 8388608L
#undef net_sf_jdshow_Com_WS_DLGFRAME
#define net_sf_jdshow_Com_WS_DLGFRAME 4194304L
#undef net_sf_jdshow_Com_WS_VSCROLL
#define net_sf_jdshow_Com_WS_VSCROLL 2097152L
#undef net_sf_jdshow_Com_WS_HSCROLL
#define net_sf_jdshow_Com_WS_HSCROLL 1048576L
#undef net_sf_jdshow_Com_WS_SYSMENU
#define net_sf_jdshow_Com_WS_SYSMENU 524288L
#undef net_sf_jdshow_Com_WS_THICKFRAME
#define net_sf_jdshow_Com_WS_THICKFRAME 262144L
#undef net_sf_jdshow_Com_WS_GROUP
#define net_sf_jdshow_Com_WS_GROUP 131072L
#undef net_sf_jdshow_Com_WS_TABSTOP
#define net_sf_jdshow_Com_WS_TABSTOP 65536L
#undef net_sf_jdshow_Com_WS_MINIMIZEBOX
#define net_sf_jdshow_Com_WS_MINIMIZEBOX 131072L
#undef net_sf_jdshow_Com_WS_MAXIMIZEBOX
#define net_sf_jdshow_Com_WS_MAXIMIZEBOX 65536L
#undef net_sf_jdshow_Com_WS_TILED
#define net_sf_jdshow_Com_WS_TILED 0L
#undef net_sf_jdshow_Com_WS_ICONIC
#define net_sf_jdshow_Com_WS_ICONIC 536870912L
#undef net_sf_jdshow_Com_WS_SIZEBOX
#define net_sf_jdshow_Com_WS_SIZEBOX 262144L
#undef net_sf_jdshow_Com_WS_OVERLAPPEDWINDOW
#define net_sf_jdshow_Com_WS_OVERLAPPEDWINDOW 13565952L
#undef net_sf_jdshow_Com_WS_POPUPWINDOW
#define net_sf_jdshow_Com_WS_POPUPWINDOW -2138570752L
#undef net_sf_jdshow_Com_WS_CHILDWINDOW
#define net_sf_jdshow_Com_WS_CHILDWINDOW 1073741824L
#undef net_sf_jdshow_Com_WS_TILEDWINDOW
#define net_sf_jdshow_Com_WS_TILEDWINDOW 13565952L
#undef net_sf_jdshow_Com_CLSCTX_INPROC_SERVER
#define net_sf_jdshow_Com_CLSCTX_INPROC_SERVER 1L
#undef net_sf_jdshow_Com_CLSCTX_INPROC_HANDLER
#define net_sf_jdshow_Com_CLSCTX_INPROC_HANDLER 2L
#undef net_sf_jdshow_Com_CLSCTX_LOCAL_SERVER
#define net_sf_jdshow_Com_CLSCTX_LOCAL_SERVER 4L
#undef net_sf_jdshow_Com_CLSCTX_INPROC_SERVER16
#define net_sf_jdshow_Com_CLSCTX_INPROC_SERVER16 8L
#undef net_sf_jdshow_Com_CLSCTX_REMOTE_SERVER
#define net_sf_jdshow_Com_CLSCTX_REMOTE_SERVER 16L
#undef net_sf_jdshow_Com_CLSCTX_INPROC_HANDLER16
#define net_sf_jdshow_Com_CLSCTX_INPROC_HANDLER16 32L
#undef net_sf_jdshow_Com_CLSCTX_RESERVED1
#define net_sf_jdshow_Com_CLSCTX_RESERVED1 64L
#undef net_sf_jdshow_Com_CLSCTX_RESERVED2
#define net_sf_jdshow_Com_CLSCTX_RESERVED2 128L
#undef net_sf_jdshow_Com_CLSCTX_RESERVED3
#define net_sf_jdshow_Com_CLSCTX_RESERVED3 256L
#undef net_sf_jdshow_Com_CLSCTX_RESERVED4
#define net_sf_jdshow_Com_CLSCTX_RESERVED4 512L
#undef net_sf_jdshow_Com_CLSCTX_NO_CODE_DOWNLOAD
#define net_sf_jdshow_Com_CLSCTX_NO_CODE_DOWNLOAD 1024L
#undef net_sf_jdshow_Com_CLSCTX_RESERVED5
#define net_sf_jdshow_Com_CLSCTX_RESERVED5 2048L
#undef net_sf_jdshow_Com_CLSCTX_NO_CUSTOM_MARSHAL
#define net_sf_jdshow_Com_CLSCTX_NO_CUSTOM_MARSHAL 4096L
#undef net_sf_jdshow_Com_CLSCTX_ENABLE_CODE_DOWNLOAD
#define net_sf_jdshow_Com_CLSCTX_ENABLE_CODE_DOWNLOAD 8192L
#undef net_sf_jdshow_Com_CLSCTX_NO_FAILURE_LOG
#define net_sf_jdshow_Com_CLSCTX_NO_FAILURE_LOG 16384L
#undef net_sf_jdshow_Com_CLSCTX_DISABLE_AAA
#define net_sf_jdshow_Com_CLSCTX_DISABLE_AAA 32768L
#undef net_sf_jdshow_Com_CLSCTX_ENABLE_AAA
#define net_sf_jdshow_Com_CLSCTX_ENABLE_AAA 65536L
#undef net_sf_jdshow_Com_CLSCTX_FROM_DEFAULT_CONTEXT
#define net_sf_jdshow_Com_CLSCTX_FROM_DEFAULT_CONTEXT 131072L
#undef net_sf_jdshow_Com_CLSCTX_INPROC
#define net_sf_jdshow_Com_CLSCTX_INPROC 3L
#undef net_sf_jdshow_Com_CLSCTX_ALL
#define net_sf_jdshow_Com_CLSCTX_ALL 23L
#undef net_sf_jdshow_Com_CLSCTX_SERVER
#define net_sf_jdshow_Com_CLSCTX_SERVER 21L
/*
 * Class:     net_sf_jdshow_Com
 * Method:    CoInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jdshow_Com_CoInitialize
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_jdshow_Com
 * Method:    CoUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jdshow_Com_CoUninitialize
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_jdshow_Com
 * Method:    CoCreateInstance
 * Signature: (Lnet/sf/jdshow/GUID;JILnet/sf/jdshow/GUID;[J)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jdshow_Com_CoCreateInstance
  (JNIEnv *, jclass, jobject, jlong, jint, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
